### ISSUE TITLE
Clarification on the type of Slack token used in documentation

### ISSUE THREAD

**Issue by wanejen** [Cubit-Studios/Swarm-SlackNotify#1]
Hi,

I am setting up the Swarm-SlackNotify project and noticed that the documentation mentions a Slack token. Could you please clarify which type of Slack token is required for this integration? You can refer to the different token types listed in Slack's documentation here: https://api.slack.com/concepts/token-types.

Thank you!

**Comment by Deams51** [comment]
Hi, I've updated the readme with more details and the new scopes the app uses.
It's an oauth token for the app, that you can retrieve once the app has been installed to a workspace. 
More info: https://api.slack.com/authentication/oauth-v2

**Comment by wanejen** [comment]
Hi,

Thank you for your prompt response to my issue. I have followed the instructions you provided and configured the settings as suggested. However, I am still experiencing issues where Slack is not receiving any information, and I am not seeing any relevant output in the logs.

To assist with diagnosing the problem, I have attached screenshots of the current configurations for your reference. Additionally, here are some details about the environment:

`
root@018cd8f9548d:/opt/perforce/swarm/module/SlackNotify/config# ls -l
total 12
-rw-r--r-- 1 root root 2036 Nov 21 08:16 module.config.php
-rw-r--r-- 1 root root  489 Nov 21 08:16 module.config.php.example
-rw-r--r-- 1 root root  526 Nov 21 08:28 slack-notify.config.php
root@018cd8f9548d:/opt/perforce/swarm/module/SlackNotify/config# cat slack-notify.config.php
<?php
/**
 * Example configuration for SlackNotify module
 * Copy this file to your Swarm config directory and adjust as needed
 */
return [
    'slack-notify' => [
        // OAuth token for your Slack app (REQUIRED)
        'token' => 'xoxb-xxx,

        // Channel for new review notifications (REQUIRED)
        'notify_channel' => 'swarm-notify',

        // Cache time for user mappings in seconds (OPTIONAL, defaults to 3600)
        'user_cache_ttl' => 3600,
    ]
];

root@018cd8f9548d:/opt/perforce/swarm/config# cat custom.modules.config.php
<?php
\Laminas\Loader\AutoloaderFactory::factory(
    array(
        'Laminas\Loader\StandardAutoloader' => array(
            'namespaces' => array(
                // ... other modules ...
                'SlackNotify'       => BASE_PATH . '/module/SlackNotify/src',
            )
        )
    )
);
return [
    // ... other modules ...
    'SlackNotify',
];
`

![image](https://github.com/user-attachments/assets/0a75b727-c601-47f7-bc5e-32896472fe5f)
